---
output:
  word_document: default
  html_document: default
---
1. Generalized Additive Model assuming a Negative Binomial distribution to account for overdispersion of deaths during the period we study[1]. The model includes a log-linear long term trend over weeks since start of observation ($\mathrm{time}$) by $\mathrm{sex}$ and $\mathrm{age}$, cyclical penalized splines for the seasonal effect over week-of-year ($\mathrm{week}$), penalized splines for the age effect, and a smooth interaction between age and seasonality. The smooth effects are stratified by sex. Indicator variables have been added for the first and last weeks of a year and for week 22 ($\mathrm{day}$). The effect for these "special days" is estimated by age and sex. The basic structure of the model is as follows:

$$
\begin{aligned}
\log\mathrm{E}\left[Y_t/\theta_t\ \right] = &\beta_0 + \beta_{\mathrm{day \times sex \times age}}(\mathrm{day\times sex\times age}) + \beta_{\mathrm{time \times sex \times age}}(\mathrm{time \times sex \times age}) +\\
&f_1(\mathrm{age | sex}) + f_2(\mathrm{week | sex}) + f_3(\mathrm{week, age}),\\
&Y_t \sim \mathrm{Neg. Bin},
\end{aligned}
$$

Where $\mathrm{E}\left[Y_t \right]$ are the expected deaths in a given week, $\theta_t$ are the exposure times, and $f_i$ are smooth functions.

2. The second approach is a Generalized Additive Model assuming a Poisson distribution with the same structure as above.

3. The third approach is a Generalized Linear Model assuming a Poisson distribution used to estimate baseline mortality during influenza epidemics and known as Serfling model[2,3]. The basic structure of the model is as follows:

$$
\begin{aligned}
\log\mathrm{E}\left[Y_t/\theta_t\ \right] = &\beta_0 + \beta_{\mathrm{day \times sex \times age}}(\mathrm{day\times sex\times age}) + \beta_{\mathrm{time \times sex \times age}}(\mathrm{time \times sex \times age}) +\\
&\beta^1_{\mathrm{week \times age \times sex}}\left(\sin\frac{\mathrm{week}2\pi}{52}\times \mathrm{age} \times \mathrm{sex}\right) + \beta^2_{\mathrm{week \times age \times sex}}\left(\cos\frac{\mathrm{week}2\pi}{52}\times \mathrm{age} \times \mathrm{sex}\right) +\\
&\beta^3_{\mathrm{week \times age \times sex}}\left(\sin\frac{\mathrm{week}2\pi}{26}\times \mathrm{age} \times \mathrm{sex}\right) + \beta^4_{\mathrm{week \times age \times sex}}\left(\cos\frac{\mathrm{week}2\pi}{26}\times \mathrm{age} \times \mathrm{sex}\right),\\
&Y_t \sim \mathrm{Pois.},
\end{aligned}
$$

4. We constructed an empirical baseline mortality based on the average mortality rate over the previous five years 2015-19 within each week and stratum. The associated deaths from this approach result from multiplying the average death rates by the population exposed to the risk. 



